sudo: required
language: python
python:
- '3.4'
- '3.5'
env:
  global:
  - CF_APP=forecast-staging
  - CF_API=https://api.cloud.gov
  - CF_USERNAME=18f-acq_deployer
  - CF_ORGANIZATION=18f-ACQ
  - CF_SPACE=staging
  - secure: SO0O2mH6ynnF8p/xBxBomwDpFE+GzS+oCQ1krukRhXbLJtALSporX1dV9dnLfPs8K2FBIyxN4neFhSvmqtqJ3PpC78+EaBaqjdpV6Kxzenibyl/yQd412ojBQ3T1EKGqSyKFFcXjnHPODMEZ2e5NeVBXd2stULDbEwbhHxO5pyWwMTAJcEW2d5v4TGgy3u070XUWFuN62T8d81rBVpK/oB54NklHCVLVYMZ6pXrhue6Xk3A4lEx975XIa6hBphyNedt5fyK0IEbfqyJmopOzp13eqySIcNo0pjnmEoOpzMvxWCB4mAIOD+7K0raVV9hI2Ltrr6AFs2GAFBqS5CnTl853RXnSCCBqD4QVM5E5LWY1S2z3/3m9XCKBQzrQlhHJwP4Kpxu2m7wEo10pe+E63+8mvwe6JiB801WkvW/NJrUr28xZqNuhWV36d1tSNCF8nxAdIziJBTSc9l76L9t610WnDkeGY3BUZ8vbez6rfgc66Dv5e6iqXIDdpylwaiMclAinwcUaRnT6pbJeJH0Zb0EpmHvnw/nUVKwIHCuoL3JMEBaOlnV8cEEe7j3eEt6kJIIqeZOJGhmTktXdyTWXzlSYTr6MmgSz3G5yTz37oTrOnV4mxG4ReFIrf2uBoG8G6EuCjul+BpIRNbntLi2wixD+bJQ1q6XEoCNdghqyJZQ=
before_install: pip install codecov
install: pip install -r requirements.txt
cache:
  directories:
  - "$HOME/.cache/pip"
before_deploy: npm install -g cf-blue-green
deploy:
- provider: script
  script: cf-blue-green-travis
  on:
    branch: feature/cf-deploys
script: cd forecast-admin/forecast && py.test --cov opportunities --cov-report term-missing
after_success:
- codecov
- coveralls
