sudo: required
language: python
python:
- '3.4'
- '3.5'
env:
  global:
  - CF_APP=forecast-staging
  - CF_API=https://api.cloud.gov
  - CF_USERNAME=18f-acq_deployer
  - CF_ORGANIZATION=18f-ACQ
  - CF_SPACE=staging
  - secure: AOQ3DkPmuJ5vcRU/KWd+tgnKsOmvnmlKRgmf9LS9I10qPs2FTY7IMiAPFtEAHAqcd759gt3du5G2AK6K27MuD68omtdeXhwZjnBEXbcuTGsSef37cyVgWHTw81opWZyyN5iTVb59r8KOS6tNRZFAyLf7Ppp+strDclRQnCili0rtc7P2OemCRzM7V3llAi5kDarNIHM4PDUVzRZ9HG67LD/kHMNmWGb8RRJU8bmNbsx4n9GCkRZApqm6LarHACdkndqM3L+nmOTGC7m2DDnDlKVUewryuyGEllGcXXxPhKrVKMOpcpE/hYoRjYenToETC3abkJ33CH0LumbQH3VGT+yiMB9zeZfhvm7YTMR0MaaQNr2fRYhVc7aUJK8XqpNWg9IIF2DVTb4URTl9zURklX4Fy6fOg90UTEqD55+1e+dcPlSPR4taA17G3y11lFz3dyLLyaQiKlLuRRHW8Yj4VBEWsbpUTXOQtrPis/sJjM0g4H1empt3WsRCfgF+re8fM2Z8rXHV7BEQvofouYZYWHpPDG+yfosFtGgwz6JKNGj1Wi+w9WWF6J7RhOsu7P3LjXRj/PSq5tQx1OuwqPu5gpCv8Dso4URteHAhsJlf4iBLNtBsHm5cms/T59jNCCuJ17HJP7n1RI4y9p9Rw8dXmzxalZBYH+b1xNQc69Nd87w=
before_install: pip install codecov
install: pip install -r requirements.txt
cache:
  directories:
  - "$HOME/.cache/pip"
before_deploy: npm install -g cf-blue-green
deploy:
- provider: script
  script: cf-blue-green-travis
  on:
    branch: feature/cf-deploys
script: cd forecast-admin/forecast && py.test --cov opportunities --cov-report term-missing
after_success:
- codecov
- coveralls
