sudo: required
language: python
python:
- '3.4'
- '3.5'
env:
  global:
  - CF_APP=forecast-staging
  - CF_API=https://api.cloud.gov
  - CF_USERNAME=18f-acq_deployer
  - CF_ORGANIZATION=18f-ACQ
  - CF_SPACE=staging
  - secure: fQFIipLTsI4UOs79HtAJIYR3DiqfP/sU+W5Lv2LI531izdGF46I7Y/gbhW39o2AXEJSxLZbepC3c9f/7dKwfcvgV3UYbxkep5x5aekM43wN/YASZrAlFyqJbG0KF3l+27Eo7ZCGLaGGF3Ilwe+gOkWnGYbnZ9hY1e0QjjdsogqzegrpprGTj9Pg/WpQYTaUchijRemGc17REOcO6C6sUozTFy/5DROBW/ELLjG2a/KVQRp7muiJ89BCVfmq33Huv8jWj3iw3tmDZPHyvEmSUew9fZbTiiZ1pSU4BoZfDaRAB8yWl9Jm/pKVw8ao8deGknEKBHNFUV2/O+Xx4p/626xDhVsgrLnj+JFVwsAFNq0F1zFszglgRE3mAz/ohi7VSREJtSLz0GAn6DhnjX3GKr4qhDV6KXeYYRJXW3r0yzIFRlKyqoA7XPo5z/V21839aHCBQJtjg3wnL3ZkYumIsUY12CdeP4bvig1u8enH5pqbBG2zuRRD0ZaMBmE8ccYR5olzf4qdHg2x/B+70T0AkJ7bXGpzw7ooscxogVltjZ3pV1JIFW4oHsAJqM0qjuSjgQ+5sCsHlKhHueF4wnd35OaI+lp0ENFyUkd+f562vP+MNb+mUwOErzWKDdRQzIdHTK4Pn8/ZUjr0h2pMS/rm65NuyVNdsjgwUKkx1B5RvNnY=
before_install: pip install codecov
install: pip install -r requirements.txt
cache:
  directories:
  - "$HOME/.cache/pip"
before_deploy: npm install -g cf-blue-green
deploy:
- provider: script
  script: cf-blue-green-travis
  on:
    branch: feature/cf-deploys
script: cd forecast-admin/forecast && py.test --cov opportunities --cov-report term-missing
after_success:
- codecov
- coveralls
